spring:
  application:
    name: RouteTracer
  Jackson:
    serialization:
      write-dates-as-timestamps: false
  flyway:
    baseline-on-migrate: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/transport_company_db}
    username: ${SPRING_DATASOURCE_USERNAME:${USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    database: PostgreSQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  freemarker:
    expose-request-attributes: true
    cache: false
    # Чтобы FreeMarker видел правки .ftlh с диска
    prefer-file-system-access: true
    settings:
      template_update_delay: 0
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 80MB
server:
  port: 8080
